---
title: "Õpetaja"
output:
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
---

Legendi järgi sünnitati 1978. aasta kaheksandas aprillipäevas kuni kella 21:30'ni Tallinna Sünnitusmajas poissi, keda hakati vanemate nimede järgi kutsuma Kalmeriks. Mina sellest mitte midagi ei tea. Esimene mälestus on lapsevankrist keha vanaisa nägemine. Elasin selle nime all palju aastaid, mille kestel ladusin endale hariduslikku baasi ümbritseva maailma mõistmiseks Tallinna 37. Keskkoolis ja hiljem ülikoolides. Mulle meeldisid väga matemaatika ja saksa keel. Arvutid olid 1990-ndates aastates keskklassi inimeste jaoks veel rariteetsed ja kui ma sain ühe enda keha ema omaniku Merikese töökaaslase kontoris arvutit kasutada, et sellega kujundada reklaam, tegin seda õhinaga. Mulle meeldis ka kodus olnud kirjutusmasinaga tekste paberile toksida, ometi lisas arvuti protsessi palju mõnu, sest kirjutatut sai hõlpsasti muuta. Samuti sai arvutiga vektorgraafilisi pilte joonestada, kuigi ma mõistet *vektorgraafika* muidugi ei tundnud. Kui Merikese teine tuttav oli Rootsist oma keha poja omanikule arvuti kaasa ostnud, läksime neile külla, et saaksin arvutimänge mängida. See oli minu jaoks väga huvitav külaskäik. Kui koolikaaslaste seas said populaarseks munadepüüdmise elektronmängud, tahtsin endale ka sellist. Merike sebiski mulle sellise ühe meie majanaabri onu mati kaudu 23 * rubla eest Venemaast. Kui klassikaaslae mängus püüdis mune Miki ja Minni ergutas teda, siis minu mängus oli munadepüüdjaks kuulus Idaploki multikakangelane hunt ja muidugi ergutas teda jänes. Sain ka oma käe peal kanda mitmeid elektronkelli, millest ühele olid seierid lausa joonistatud. Nimetatud koolis lubati meile arvutiõpet. Üks klassiruum oli varustatud *Juku*dega ja üks International Business Machinesi masin oli seal ka. Saime veidi vektorgraafikas joonestada ja sisu mustritega täita. Õpetaja andis meile ülesandeks: "Konstrueerige kell!", viis meiega läbi ühe küsitluse ja kadus. Keskkooli ajal tahtis eesti keele ja kirjanduse õpetaja eve levand, et meie klassi arvutiguru tarvo kurm talle vastloodud internetist kõikvõimalikkud esseeteemalised lehed välja trükiks. Ma ei saanud toona aru, miks tarvo selle peale õpetajalt täpsustust küsis. 1996. aastas sebis Merike omale järjekordse tutvuse. See võis ka juba varem juhtunud olla, igatahes haarati meid võrkturundussüsteemi nimega Golden NeoLife Diamite International. Kuidas veenis Merike üht kirjanikust miljonäri minu valdusse üht kolmevärvilise kuvariga kohverarvutit andma, et ma saaksin reklaame teha. Mis sa arvad, millised need värvid olid? Oranž, sinine ja valge. Kui see arvuti enam Random Access Memory't (RAM) kasutada ei suutnud, leidis Merike uue võimaluse minu kasutada ühe juba korraliku ja kaasaegse arvuti osta. See oli 100 * MHz ühetuumalise *Pentium*-protsessoriga arvuti, milles oli RAM'i 16 * MB, kõvaketta mälu 1.6 * GB. Tänapäeval võib olla valus mõelda, kuidas sellist masinat kasutada, aga toona mulle sellest täiesti piisas. Või siis mitte täiesti, sest 1997 ma juba õppisin ülikoolis neid asju, mida tänapäevas põhikoolides õpetatakse - kontoritarkvara kasutama - ja ma olin nördinud, et koos 5000 * EEK kuvariga 21000 * EEK maksnud uhiuues arvutis ei olnudki *Word*i. Selgus, et see sisalduvat kontoritarkvara paketis nimega *Microsoft Office*, mis tulevat eraldi osta. Ma lasin saja või 150 krooni eest sama poe tegelasel mulle piraatplaadi teha. Sain talt *Corel DRAW*' ka Kui ükskord järjekordsele plaadile järele läksin, teda polnud, aga tema boss oli väga asjalik mind aitama. Kui piraatlusest kuulis, paistis ta väga pettunud olevat. Ma ei tea, mida tolle töötajaga tehti. Leidsin omale muu tarnija, kes võeti vist hiljem mitmekordselt politseitegelaste poolt vahele. Kasutas muuseas nime Mario Pastel. Tal oli isegi vastavanimeline pangakonto. Kuna mul oli kodus korralik kaasaegne arvuti, tekkis huvi sellest kõikvõimalikku välja pigistada. Aastaid mängisin *Doom*i, *Heretic*'u, *Hexen*it ja oma lemmikarkaadmängu *Duke Nukem 3D*, mille peategelane peale vetsupotil käimist teatas: "Much better!" Hiljem jäin sõltuvusse *Warcraft*ist, *Dune*st ja *Transport Tycoon Deluxe*'st. Hakkasin iseseisvalt õppima, kuidas veebilehti teha. Sebisin omale ise sissehelistamise teenusena internetiühenduse MicroLink Online'st. Kuus sain kasutada 20 * h. Seega telefoneerisin sisse, tirisin uued meilid alla, katkestasin ühenduse, kirjutasin vastused, ühendusin uuesti ja saatsin vastused. Ühenduskiirus oli 33.6 * kB / s ja ühe MP3-faili sain alla tiritud poole tunniga. Arvuti maailm oli niivõrd huvitav, et valisin ülikoolis ärikorralduse õppesuunas kitsama valdkonna majandusinformaatika ja asusin õppima Visual BASIC't (VB), mille sain ka Theodor Luczkowski käe all selgeks. Selle baasil õppisin ka Active Server Pages'i ja lõin oma esimese dünaamilise sisuhalduse süsteemi. 2000 meelitati mind minu esimesele regulaarsele arvutialasele palgatööle Index Net'i, kus asusin progejaks-testijaks testaja brutokuupalgaga 5000 * EEK, mida hiljem suurendati 7000 * EEK peale. E-kommertsi mull lõhkes ja Index Net pankrotistus. Mind korjati üles TietoEnator Eesti punti, kus kasutasin oma VB' ja *Microsoft Access*'i oskusi, kuid vajalikku Javat ma toona ära ei õppinud. Ärikorraldus oli minu jaoks niivõrd igavaks muutunud, et tahtsin lausa õppesuunda vahetada bakalaureuseteose jaoks. Siiski lõpetasin teemaga *Muusikatööstus tänapäeva majanduses* ja asusin kümneks kuuks nautima Šveitsi võlusid, kus Baseli Ülikoolis haarasin endale mõned majandusinformaatika kursused, palju keelekursuseid, tennist ja mind liideti ka ühte projekti, kus puutusin kokku toona uudse tehnoloogiaga, et luua õppesüsteem, milles saaks nt keemiliste ühendite skeeme koostada. Loogiliselt järgnes õppimine Tallinna Tehnikaülikooli (TTÜ) informaatikamagistratuuris, mille lõpetasin magistriteose *Talitluspunktide analüüs TTÜ Spordiportaali näitel* esitlemisega. Järjepanu tegin palgatööd eri tööandjate juures, kuni oli selge, et see mulle ei sobi. 2010 võtsin enda isiku töötuna arvele, koostasin äriplaani ja 2011 lõin oma esimese ja seni ainsa osaühingu nimega TOMEKIT. Sai selgeks, et ka allhankijana mul ei istu hästi tegutseda. Tegin aegajalt projekte suheldes otse tellijatega. Kui 2005 võtsime kristo tullusega valdur topaasialt üle Eesti Üliõpilaste Meistrivõistluste Tennises korraldamise, asusin oma sisuhaldussüsteemi looma, mida hiljem korduvalt nullist ümber kirjutasin. Tennises olen oma informaatikaoskusi lausa painajalikult rakendanud.

2010 veenis teisel pool minu korteri seina asuv tarmo lai mind koos temaga tennisetreeneriks õppima. Sain lausa litsentsi. 2014 veenis ühel TTÜ Vilistlaskogu välisõppimise sündmuses minuga tuttavaks saanud terje tammekivi mind asuma õpetama seda, mida olin juba üle kümne aasta praktiseerinud - erinevaid tarkvara loomisega seotud teemasid kutsekoolis. Kui olin sellega Pärnu Saksa Tehnoloogiakoolis kaks aastat tegelenud, suundusin sama kauaks Audentesesse, et katta International Baccalaureate'i Diploma Programme's ära täielikult Computer Science. Samaaegselt turgutasin Tallinna Polütehnikumi õpilasi sarnaste teemadega nagu Pärnus. 2018 otsustasin oma teenustepakkumise assortiid laiendada matemaatikaõpetamisega Tallinna Kunstigümnaasiumis (TKG), kus viisin läbi ka programmeerimise erikursuseid ja valdkonnakohaseid projektisündmusi. Üheaegselt toimetasin Harkus ja peagi juba ka Peetri Lasteaed-Põhikoolis arvutiteaduse klubisid. Viimases õpetasin ka matemaatikat ja digiõpet. TKG'st lahkununa sain omale esimese üks-ühele matemaatikaõpilase, kes alustas minuga, kui ta õppis seitsmendas klassitasemes. Ta on siiamaani mu õpilane ja nüüd õpib ta juba kümnendal klassitasemel. Millalgi viisin läbi hajusrakenduste aluste kursuse Ida-Viru Kutsehariduskeskuses. Ja siis ma avastasin, et Tabasalu Ühisgümnaasiumisse otsitakse õpetajat, kes õpetaks korraga nii matemaatikat, geograafiat, füüsikat, bioloogiat kui keemiat. Uurisin, kus selle kõige õpetajaks õppida saab ja leidsin integreeritud loodusteaduste õppekava Tallinna Ülikoolis, kus 2021. aasta sügisest lisaks tohutule kogusele vahepealsetele õpetajakoolitustele omandan oma kolmandat kõrgharidust tehes seda esmakordselt täie mõnuga ja selge sihiga saavutada kümmekonna aastaga piisav baas õpetamaks mitte ainult tennist, arvutiteadust ja matemaatikat, vaid ka nende kõikide lõimimiseks baasloodusteadustega ja loomaks variatsiooniteoorial ja vaiksel õpetamisel põhineva universaaltarkvara iseõppimiseks.

Lisaks eelmainitud tegevustele meeldib mulle väga orienteeruda ja ka seda lõimida nii informaatika, matemaatika kui tervisega. Leian, et lastele tuleks juba maastmadalast õpetada tantrat ehk üksteise austamist. Muidugi meeldib mulle nautida õpitud ja praktiseeritud kama sutra tehnikaid ja ladina-ameerika tänavatantse, millest lemmik on batšaata ja ega rueda de casino väga maha jää! Jalgrattaid olen vahelduva eduga erinevalt utiliseerinud. Nt kaks aastat sõitsin aastaringselt mis tahes ilmaga. Üks ekstreemne näide oli nt, kui sõitsin Harkust TKG juurde, et seal õpetada, sealt Peetrisse, et seal õpetada, misjärel tugevas vihmasajus Tiskresse, et seal õpetada ja lõpuks Harkusse tagasi muidugi ka. Tänapäevas naudin siiski rohkem hea kiirendusega *Peugeot 308* isendit, millega saab kiiremini ja rohkem, sõltub muidugi, mida. Minu peamine kehv omadus on, et mulle meeldib liiga palju maailma uurida ja olla selles põhjalik, mistõttu on liiga paljud ettevõetud tegevused lõpetamata. Nüüd ma siiski keskendun ja teen asjad korralikult, sest nii on tulemus tõeliselt nauditav ja teised on ka rahul. Hästi oluline on minu jaoks, et inimesed tahaksid, suudaksid ja oskaksid elada üksteise sootsiumis inimsõbralikult. Leian, et selle jaoks on ainusobiv majanduslik vorm jagamisühiskond. Ühtlasi olen mõistnud, et siinses reaalsuses ei pruugi see võimalik olla. Ega enne teada ei saa, kui ei saa või saab! Ahjaa, matkata meeldib ka, eriti subtroopikas ja üldse vingetes kohtades. Ja lävida inimestega, kes mind konformismi tagasi ei kisu. Kuigi olen oma ideedega *tädi maalist* nii palju ees, et ta ei saa minust aru, leidub vahel inimesi, kes mind mõistavad, ja kellega on nauding sama teelõiku kõndida või kasvõi sama missiooni ajada. Mission always comes first.

Ja juba mitu aastat olen ma leitav nime peacecop kalmer: kaudu. Kõik tähed on selles väikesed ja ainult nii tohib mu nime kirjutada. Lõpus on suveräänikoolon, mis eraldab minu nime minu esindatava hõimu nimest. peacecop kõlab nagu selle hõimu nimi, kuhu minu keha legendi järgi sünnitati - Piiskop. Lisaks iseloomustab see mu missiooni. Olen suveräänina elada sooviv inimene.
