---
title: "Arvutiteadus"
output:
  bookdown::html_document2:
    toc: TRUE
    toc_float: TRUE
---

Arvutiteadus on arvutamise uurimine. Tegemist on loodusteaduste peale ehitatud teadusega, mis põhineb matemaatikale ja psühholoogiale.

Kui eelmises sajandis hakati arvutiteadust õpetama alles kõrgkoolis või tehnikumis, siis tänapäevas õpitakse seda juba enne üldhariduskooli esimest õppeaastat. Vaatamata sellele ei ole tehnikumi- või kõrgkoolieelne informaatikaõpe nii põhjalik kui teiste teaduste õpe. Arvutid on juba tavaline osa meie kui inimeste elus. Nii saab ka endale vajadusel leida internetist sobiliku kursuse ja ise õppida. Mina õppisin informaatikat kõrgkoolis ja olen informaatikamagister. Olen selles valdkonnas töötanud alates aastast 2000 olles valdkonna temaatikat õpetanud nii eesti kui inglise keeles, millest viimases International Baccalaureate'i Diploma Programme'i Computer Science'i tervikkava järgi nii standard- kui kõrgel tasemel. Naudin nii isetegemist kui oma oskuste õpetamist teistele, mis on võimalus veel paremini osata. Kaasan informaatikat oma muudessegi tegevustesse. Olen aastaid juhendanud arvutiteaduse klubisid. Siia lehele olen hakanud koondama oma portfooliot ja õppekavasid. Õppesisu on eraldi staatilisel saidil, mille iga huvitatud õpilane iseseisvalt oma arvutisse üles seab. Õpetan nii üks-ühele kui inimesi rühmas. Standardtasu, kui pole ahvatlevamat ettepanekut, on 40 * eurot / h ja tavaliselt tegutseme 1.5 * h järjest tehes iga tund 5 kuni 15 * minutit silmadele ja mõistusele pause. Kui sõidan Harkust kaugemale kui pool tundi, küsin iga poolele tunnile järgneva veerandtunni transpordi eest 10 * eurot lisa. Valides minu õpetajaks saad sa vajadusel kaetud mitu arvutiteaduse valdkonda, lisaks matemaatika, tennise, nüüd juba ka mingil määral keemia ja füüsika, samuti keeled ühe ja sama inimese abil ega pea otsima erinevaid, igaühega eraldi kokku leppima ja arveldama. Tegutsen nii oma kodus Harkus, õpilase asukohas kui ka neutraalsel pinnal. Aegajalt viin läbi ka õpetamist või juhendamist interneti kaudu. Minuga saab kõige kiiremini ühendust telefoneerides aadressile 56204556. Olen ühendatav ka [meilitsi](mailto:kalmer@test.tennis24.ee), samuti kasutan *Whatsapp*i ja *Telegram*i. Ahjaa, kasutan igal võimalusel tasuta ja avatud lähtekoodiga tarkvara, sest see on igaühele kus tahes maailma osas ilma liigsete pingutusteta kättesaadav, mistõttu õpetan meeleldi ka Microsofti ja Apple'i sõltlasi ümber *Ubuntu*t kasutama.
